variable "projectID" {  }
variable "key_file" {  }
variable "project_region" {  }
variable "firewall_name" {  }
variable "allowed_ip_range" {  }
variable "allowed_port" {  }
variable "vpc_network_name" {  }
variable "virtual_machine1_name" {  }
variable "virtual_machine1_type" {  }
variable "virtual_machine1_zone" {  }
variable "virtual_machine1_os_image" {  }
variable "virtual_machine1_boot_disk_type" {  }
variable "virtual_machine1_boot_disk_size" {  }
variable "virtual_machine2_name" {  }
variable "virtual_machine2_type" {  }
variable "virtual_machine2_zone" {  }
variable "virtual_machine2_os_image" {  }
variable "virtual_machine2_boot_disk_type" {  }
variable "virtual_machine2_boot_disk_size" {  }
variable "load_balancer_frontend_name" {  }
variable "load_balancer_frontend_port" {  }
variable "instance_group_pool_name" {  }
variable "load_balancer_health_check_name" {  }
variable "load_balancer_health_check_request_path" {  }
variable "health_check_port" {  }
